# Generated by Django 3.0.3 on 2020-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('YE', 'Yndunvac e'), ('YD', 'Yndunel e'), ('BE', 'Berum e')], max_length=30, null=True, verbose_name='Status'),
        ),
    ]
